export const UPDATE_CART_CONFIG = 'UPDATE_CART_CONFIG';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const UPDATE_CART_ID_STATUS = 'UPDATE_CART_ID_STATUS';